"""
Shared Typed State for LangGraph Autonomous Investigation Workflow.

Defines the complete, typed state channels passed between nodes in the
LangGraph execution graph, supporting:
- Multi-agent orchestration
- Parallel branch state updates
- Dynamic planning & subtasks
- Evidence evaluation and conflict tracking
- Hypothesis verification
- Resource tracking and loop/deadlock detection
- Seamless session memory integration
"""

from typing import Any, Dict, List, Literal, Optional, TypedDict
from pydantic import BaseModel, Field
from datetime import datetime, timezone

from app.agent.state import (
    CompanyCardData,
    NewsArticle,
    ResearchPaper,
    PatentItem,
    SourceItem,
    StepActivity,
    ToolExecutionRecord,
)


class SubTask(BaseModel):
    """Specific subtask planned for dynamic execution."""
    id: str
    title: str
    tool_name: str
    tool_input: Dict[str, Any]
    target_entity: Optional[str] = None
    priority: int = 1
    status: Literal["pending", "running", "completed", "failed", "skipped"] = "pending"
    result_summary: Optional[str] = None
    error: Optional[str] = None


class EvidenceItem(BaseModel):
    """A verified factual piece of evidence extracted during research."""
    id: str
    claim: str
    source_name: str
    source_url: Optional[str] = None
    publication_date: Optional[str] = None
    reliability_score: float = 0.8  # 0.0 to 1.0 scale
    entity_tag: Optional[str] = None
    is_corroborated: bool = False


class EvidenceConflict(BaseModel):
    """Detected disagreement or contradiction across gathered evidence sources."""
    id: str
    topic: str
    claim_a: str
    source_a: str
    date_a: Optional[str] = None
    claim_b: str
    source_b: str
    date_b: Optional[str] = None
    analysis: str
    resolution_status: Literal["resolved", "unresolved", "uncertain"] = "uncertain"
    preferred_claim: Optional[str] = None
    confidence_impact: Literal["high", "medium", "low"] = "medium"


class HypothesisRecord(BaseModel):
    """Testable analytical hypothesis formulated for comparative intelligence."""
    id: str
    hypothesis_text: str
    target_entities: List[str] = Field(default_factory=list)
    supporting_evidence: List[str] = Field(default_factory=list)
    contradicting_evidence: List[str] = Field(default_factory=list)
    evaluation_score: float = 0.5  # 0.0 (falsified) to 1.0 (strongly supported)
    status: Literal["formulated", "testing", "supported", "refuted", "inconclusive"] = "formulated"
    conclusion: Optional[str] = None


class EvaluationResult(BaseModel):
    """Evaluation verdict generated by the Self-Evaluation node."""
    passed: bool
    answered_user_query: bool = True
    entities_covered: bool = True
    sources_sufficient: bool = True
    conflicts_handled: bool = True
    confidence_acceptable: bool = True
    critical_failures: bool = False
    feedback: str = ""
    suggested_replan: bool = False


class GraphInvestigationState(TypedDict, total=False):
    """
    Typed Shared State for the LangGraph Investigation Graph.
    
    Contains all state channels required for autonomous multi-agent
    execution, dynamic planning, conditional routing, parallel execution,
    recovery, and self-evaluation.
    """
    # Core User & Session identifiers
    user_query: str
    conversation_id: str
    session_id: str
    chat_history: Optional[List[Dict[str, str]]]
    
    # Context & Disambiguation
    relevant_context: Optional[Dict[str, Any]]
    investigation_goal: str
    detected_entities: List[str]
    detected_topics: List[str]
    
    # Dynamic Planning & Subtasks
    task_plan: List[Dict[str, Any]]
    subtasks: List[Dict[str, Any]]
    completed_tasks: List[str]
    remaining_tasks: List[str]
    current_phase: str
    
    # Structured Multi-Source Intelligence Results
    research_results: Dict[str, Any]
    news_results: List[Dict[str, Any]]
    research_paper_results: List[Dict[str, Any]]
    
    # Entities, Structured Objects & Citations
    collected_companies: List[Dict[str, Any]]
    collected_news: List[Dict[str, Any]]
    collected_research: List[Dict[str, Any]]
    collected_patents: List[Dict[str, Any]]
    collected_sources: List[Dict[str, Any]]
    
    # Evidence Evaluation & Hypotheses
    evidence: List[Dict[str, Any]]
    conflicting_evidence: List[Dict[str, Any]]
    hypotheses: List[Dict[str, Any]]
    confidence: Literal["high", "medium", "low"]
    
    # Self-Evaluation & Verification
    self_evaluation: Optional[Dict[str, Any]]
    evaluation_passed: bool
    
    # Errors, Tool Tracking & Resource Budgets
    tool_errors: List[Dict[str, Any]]
    tool_call_count: int
    max_tool_calls: int
    iteration_count: int
    max_iterations: int
    tools_used: List[str]
    action_history: List[str]
    repeated_action_count: Dict[str, int]
    unavailable_tools: List[str]
    
    # Activity Steps (UI Safe, Non-Chain-of-Thought)
    steps: List[Dict[str, Any]]
    
    # Synthesis & Final Response
    final_answer: Optional[str]
    status: Literal["initializing", "planning", "researching", "evaluating", "synthesizing", "replanning", "completed", "failed"]
    error: Optional[str]
    
    # Adversarial Testing Mode (Isolated Development Configuration)
    adversarial_config: Optional[Dict[str, Any]]
    
    # Observability & Tracing Context (Task 7)
    trace_id: Optional[str]
    diagnoses: List[Dict[str, Any]]
